import {Router} from 'express';
import productRoutes from './product.routes.js';
import orderRoutes from './order.routes.js';
import agentRoutes from './agent.routes.js';
import authRoutes from './auth.routes.js';
import {authenticate} from '../middlewares/auth.middleware.js';
import webhookRoutes from './webhook.route.js';
const router = Router();
router.use('/auth', authRoutes);    
console.log('ROUTES INDEX CHARGE');
console.log(authRoutes);
router.use('/webhook', webhookRoutes);
router.use(authenticate);
router.use('/products', productRoutes);
router.use('/orders', orderRoutes);
router.use('/agents', agentRoutes);
export default router;