import {Router} from 'express';
import productRoutes from './product.routes.js';
import orderRoutes from './order.routes.js';
import agentRoutes from './agent.routes.js';
import authRoutes from './auth.routes.js';
import bookingRoutes from './booking.route.js'; 
import {authenticate} from '../middlewares/auth.middleware.js';
import webhookRoutes from './webhook.route.js';
import n8nRoutes from './n8n.routes.js';
const router = Router();
router.use('/auth', authRoutes);   
router.use(authenticate);
router.use('/orders', orderRoutes);
router.use('/' , n8nRoutes);
router.use('/webhook', webhookRoutes);
router.use('/products', productRoutes);
router.use('/agents', agentRoutes);
router.use('/booking', bookingRoutes);
export default router;